name: Build, Upload and Commit Release

on:
  workflow_dispatch:

jobs:
  build-upload-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel build twine
      # This ensures setuptools, wheel, build, and twine are installed

    - name: Build wheels and source distribution
      run: |
        python setup.py bdist_wheel
        python setup.py sdist
        twine check dist/*

    - name: Upload to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "API tokens can be created at https://pypi.org/manage/account/token/"
        python -m twine upload -u __token__ -p $PYPI_API_TOKEN dist/*
    
    - name: Commit Release
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        # Check if there are any changes. If there are, proceed with commit and tag.
        if ! git diff --quiet; then
          git add -A
          VERSION=$(python setup.py --version)
          git commit -m "Release v${VERSION}. [skip ci]"
          git tag v${VERSION}
          echo "A commit and tag for this release has been made."
        else
          echo "No changes to commit."
        fi
      shell: bash
