name: Lint

on:
  pull_request:  # Trigger on PRs to develop and v4
    branches:
      - develop
      - v4

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Get out of detached head state
      run: |
        git fetch origin ${{ github.base_ref }}
        git fetch origin ${{ github.ref }}
        git checkout FETCH_HEAD --
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install --upgrade ruff setuptools toml wheel

    - name: Test that ruff has been applied
      # if this check fails for your PR, run `ruff format .`
      run: |
        ruff format . --diff

    - name: Run Lint
      run: ruff check --output-format=github .

    - name: Test Packaging
      run: |
        python setup.py sdist bdist_wheel
        pip install -v .
